[package]
name = "halo2-aggregation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2wrong = { git="ssh://git@github.com/Trapdoor-Tech/halo2wrong.git", branch="agg" }
#halo2wrong = { path = "../halo2wrong" }
halo2 = { git="ssh://git@github.com/Trapdoor-Tech/halo2.git", branch="kzg-agg"}
#halo2 = { path = "../halo2" }

[dev-dependencies]
#pairing = { path = "../pairing", package = "pairing_bn256" }
pairing = { git = "ssh://git@github.com/Trapdoor-Tech/zkevm_pairing.git", package = "pairing_bn256" }
rand = "0.8"
rand_core = { version = "0.6", default-features = false }
