[package]
name = "halo2-aggregation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2wrong = { path = "../halo2wrong" }
#halo2wrong = {git = "https://github.com/trapdoor-tech/halo2wrong", branch="agg"}
halo2 = { path = "../halo2" }
#halo2 = { git="https://github.com/trapdoor-tech/halo2.git", branch="agg"}
blake2b_simd = "0.5"